Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
#    config.vm.provision "ansible" do |ansible|
#        ansible.playbook = "os_setup_dependency.yml" 

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "700"
    end

    config.vm.define "zabbixserver01" do |zabbixserver01|
        zabbixserver01.vm.network "private_network", ip: "192.168.33.10"
        zabbixserver01.vm.hostname = "zbxserver01"  
        zabbixserver01.vm.provision "shell", path: "set_root_pass.sh"
        zabbixserver01.vm.provision "ansible" do |ansible|
            ansible.playbook = "os_setup_dependency.yml" 
        end
    end
    config.vm.define "zabbixserver02" do |zabbixserver02|
        zabbixserver02.vm.network "private_network", ip: "192.168.33.11"
        zabbixserver02.vm.hostname = "zbxserver02"
        zabbixserver02.vm.provision "shell", path: "set_root_pass.sh"
        zabbixserver02.vm.provision "ansible" do |ansible|
            ansible.playbook = "os_setup_dependency.yml" 
        end
    end

    config.vm.define "zabbixserver03" do |zabbixserver03|
       zabbixserver03.vm.network "private_network", ip: "192.168.33.12"
       zabbixserver03.vm.hostname = "zbxserver03"   
       zabbixserver03.vm.provision "shell", path: "set_root_pass.sh"
       zabbixserver03.vm.provision "ansible" do |ansible|
            ansible.playbook = "os_setup_dependency.yml" 
       end
    end

#end
end
